.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2015 Zhou Mo <cdluminate@gmail.com>,
.\" (C) Copyright 2016 Boyuan Yang <073plan@gmail.com>,
.\"
.TH FORTUNE-ZH 6 "2016-08-06" "Debian Chinese Team" "游戏手册"

.SH 名称
fortune-zh \- fortune 工具的中文数据文件

.SH 大纲
.B fortune-zh

.SH 描述
\fIfortune-zh\fR 是一个简单的 shell 脚本，可以配合中文数据文件及其预设格式调用 \fIfortune\fR 
工具。

.SH 数据文件
.TP
.I /usr/share/games/fortunes/tang300
大约300首唐代诗歌。

.TP
.I /usr/share/games/fortunes/song100
大约100首宋代诗词。

.TP
.I /usr/share/games/fortunes/chinese
除了 tang300 和 song100 外的古今中外中文作品选编。

.SH 参见
.BR fortune(6)

.SH 作者
fortune-zh 的原作者是
.IP
Copyright © 2001-2009 Yu Guanghui <ygh@debian.org>
.PP
本手册页由 Zhou Mo <cdluminate@gmail.com> 为 Debian 项目编写，且可用于其它用途。
